# SPDX-License-Identifier: MIT
# From spectrometry.mp4 engines by Ethan Earl - https://github.com/ec175/spectrometry_public
"""Generate every CATALOG.md from the catalog.json files.

`engines/<name>/catalog.json` is the source of truth. Everything below is derived from it:

    engines/<name>/CATALOG.md            the full object catalogue for one engine
    engines/<name>/<frames>/README.md    a thumbnail gallery of that engine's stills
    engines/CATALOG.md                   the index across every engine

Edit the JSON and re-run:

    python tools/build_catalogs.py

This is the standard fix for a list that needs to appear in more than one place: two
hand-maintained copies of a list drift apart within about a week.
"""
from __future__ import annotations

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
ENG = os.path.join(ROOT, "engines")

ORDER = ["wind-tunnel", "field-lines", "lattice-grid", "shape-physics",
         "attractors", "oscilloscope", "chemical-scope", "academia"]


def md_escape(s):
    return str(s).replace("|", "\\|")


def table(headers, rows):
    if not rows:
        return ""
    out = ["| " + " | ".join(headers) + " |",
           "|" + "|".join(["---"] * len(headers)) + "|"]
    for r in rows:
        out.append("| " + " | ".join(md_escape(c) for c in r) + " |")
    return "\n".join(out) + "\n"


def frames_dir(cat):
    """Most engines call their stills `frames/`; academia's are figure previews."""
    return cat.get("frames_dir", "frames")


# Stamped into the top of every generated file. Without it, the first instinct on spotting a
# mistake in a catalogue is to fix the Markdown - which the next run of this script silently
# reverts, taking the correction with it.
GENERATED = ("<!-- Generated by tools/build_catalogs.py from catalog.json. "
             "Do not edit by hand. -->\n")


def build_engine(cat, engine_dir):
    fdir = frames_dir(cat)
    L = []
    a = L.append
    a(GENERATED)
    a(f"# {cat['title']} — object catalogue\n")
    a(f"> {cat['tagline']}\n")
    a(f"{cat['method']}\n")

    if cat.get("output"):
        o = cat["output"]
        a("**Output.** " + o["native"] + ". " + o.get("note", "") + "\n")

    # ---- modules
    a("\n## Modules\n")
    a("What each shipped file is. Compositions (`scenes.py` and friends) are deliberately not "
      "part of this repository — see the engine README.\n")
    a(table(["module", "kind", "what it gives you"],
            [(f"`{m['path']}`", m["kind"], m["what"]) for m in cat.get("modules", [])]))

    # ---- objects
    for group in cat.get("objects", []):
        a(f"\n## {group['group']}\n")
        if group.get("intro"):
            a(group["intro"] + "\n")
        has_frames = any(it.get("frames") for it in group["items"])
        rows = []
        for it in group["items"]:
            # some entries describe a behaviour rather than a callable and carry no signature
            s = it.get("signature")
            sig = f"`{s}`" if s and s != "—" else f"**{it['name']}**"
            row = [sig, it["what"], it.get("notes", "")]
            if has_frames:
                imgs = " ".join(f"[{i+1}]({fdir}/{f})"
                                for i, f in enumerate(it.get("frames", [])))
                row.append(imgs or "—")
            rows.append(tuple(row))
        headers = ["object", "what it is", "notes"] + (["frames"] if has_frames else [])
        a(table(headers, rows))

    # ---- scenes
    if cat.get("scenes"):
        a("\n## Compositions\n")
        a(cat.get("scenes_intro", "") + "\n")
        rows = []
        for s in cat["scenes"]:
            imgs = " ".join(f"[{i+1}]({fdir}/{f})" for i, f in enumerate(s.get("frames", [])))
            rows.append((f"`{s['name']}`", s["what"], s.get("status", ""), imgs or "—"))
        a(table(["composition", "what it does", "status", "frames"], rows))

    # ---- parameters
    if cat.get("parameters"):
        a("\n## Parameters that matter\n")
        a(cat.get("parameters_intro", "") + "\n")
        rows = [(f"`{p['name']}`", p.get("where", ""), p["meaning"], p.get("range", ""))
                for p in cat["parameters"]]
        a(table(["parameter", "lives in", "what it controls", "usable range"], rows))

    a("\n---\n")
    a("*Generated from `catalog.json` by `tools/build_catalogs.py` — edit the JSON, not this "
      "file.*\n")

    with open(os.path.join(engine_dir, "CATALOG.md"), "w", encoding="utf-8",
              newline="\n") as fh:
        fh.write("\n".join(L))


def build_gallery(cat, engine_dir):
    """A thumbnail page for the stills folder, so opening it shows pictures, not file names."""
    fdir = frames_dir(cat)
    d = os.path.join(engine_dir, fdir)
    if not os.path.isdir(d):
        return 0
    files = sorted(f for f in os.listdir(d) if f.lower().endswith((".jpg", ".jpeg", ".png")))
    if not files:
        return 0
    per_row = 4
    width = f"{100 // per_row - 1}%"
    L = []
    a = L.append
    a(GENERATED)
    a(f"# {cat['title']} — stills\n")
    a(f"[← {cat['title']}](../README.md) · [catalogue](../CATALOG.md) · "
      f"[all engines](../../README.md)\n")
    a("Frames pulled from finished renders, so you can see what each composition looks like "
      "before you install anything. Tap any image for full size.\n")

    def row(names, alt):
        cells = [f'<a href="{f}"><img src="{f}" width="{width}" alt="{alt}"></a>' for f in names]
        return "<p>\n" + "\n".join(cells) + "\n</p>\n"

    shown = set()
    for s in cat.get("scenes", []):
        fs = [f for f in s.get("frames", []) if f in files]
        if not fs:
            continue
        a(f"### `{s['name']}`\n")
        a(s["what"].split(". ")[0].rstrip(".") + ".\n")
        a(row(fs, f"{s['name']} still"))
        shown.update(fs)
    for g in cat.get("objects", []):
        for it in g["items"]:
            fs = [f for f in it.get("frames", []) if f in files and f not in shown]
            if fs:
                a(f"### {it['name']}\n")
                a(row(fs, f"{it['name']} still"))
                shown.update(fs)
    rest = [f for f in files if f not in shown]
    if rest:
        if shown:
            a("### More stills\n")
        for i in range(0, len(rest), per_row):
            a(row(rest[i:i + per_row], f"{cat['title']} still"))
    with open(os.path.join(d, "README.md"), "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(L))
    return len(files)


def build_root(cats):
    L = []
    a = L.append
    a(GENERATED)
    a("# Catalogue index\n")
    a("[← front page](../README.md) · [engine gallery](README.md)\n")
    a("Every object in this repository, grouped by the engine that makes it. Each engine's own "
      "`CATALOG.md` carries the parameters, ranges and the notes on what breaks if you change "
      "them.\n")

    a("\n## Engines\n")
    rows = []
    for c in cats:
        counts = []
        n_obj = sum(len(g["items"]) for g in c.get("objects", []))
        if n_obj:
            counts.append(f"{n_obj} objects")
        if c.get("scenes"):
            counts.append(f"{len(c['scenes'])} compositions")
        fd = os.path.join(ENG, c["engine"], frames_dir(c))
        n_frames = len(os.listdir(fd)) if os.path.isdir(fd) else 0
        if n_frames:
            counts.append(f"{n_frames} frames")
        rows.append((f"[{c['title']}]({c['engine']}/)", c["tagline"], ", ".join(counts)))
    a(table(["engine", "what it makes", "catalogue"], rows))

    for c in cats:
        a(f"\n## {c['title']}\n")
        a(f"[README]({c['engine']}/README.md) · "
          f"[catalogue]({c['engine']}/CATALOG.md) · "
          f"[stills]({c['engine']}/{frames_dir(c)}/README.md) · "
          f"[source]({c['engine']}/src/)\n")
        for group in c.get("objects", []):
            names = ", ".join(f"`{i['name']}`" for i in group["items"])
            a(f"\n**{group['group']}** — {names}\n")
        if c.get("scenes"):
            names = ", ".join(f"`{s['name']}`" for s in c["scenes"])
            a(f"\n**Compositions** — {names}\n")

    a("\n---\n")
    a("*Generated by `tools/build_catalogs.py`.*\n")

    with open(os.path.join(ENG, "CATALOG.md"), "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(L))


def main():
    cats = []
    for name in ORDER:
        d = os.path.join(ENG, name)
        p = os.path.join(d, "catalog.json")
        if not os.path.isfile(p):
            print(f"  !! no catalog.json for {name}")
            continue
        with open(p, encoding="utf-8") as fh:
            cat = json.load(fh)
        build_engine(cat, d)
        n_img = build_gallery(cat, d)
        cats.append(cat)
        n_obj = sum(len(g["items"]) for g in cat.get("objects", []))
        print(f"  {name:14s} {n_obj:3d} objects  {len(cat.get('scenes', [])):3d} compositions"
              f"  {n_img:3d} stills")
    build_root(cats)
    print(f"\nwrote {len(cats)} engine catalogues, their stills galleries, and engines/CATALOG.md")


if __name__ == "__main__":
    main()
